#Server
server:
  port: 9009
  servlet-path: /addressMigrator
spring:
  application:
    name: address-migrator
  batch:
    lightmin:
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
        classic:
          server:
            url: http://localhost:50100/lightmin-server
      batch:
        #default jdbc
        repository-type: jdbc
        #default dataSource
        data-source-name: dataSource
        #default BATCH_
        table-prefix: BATCH_

