#Server
server:
  port: 9009
  servlet:
    context-path: /addressMigrator
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: address-migrator
  batch:
    lightmin:
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
    job:
      enabled: false

