#Server
server:
  port: 9009
  servlet-path: /addressMigrator
spring:
  application:
    name: address-migrator
  batch:
    lightmin:
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
    job:
      enabled: false

