#Server
server:
  port: 9020
  servlet:
    context-path: /addressMigratorRemoteRepository
spring:
  application:
    name: address-migrator-remote-application
  batch:
    lightmin:
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
        classic:
          server:
            url: http://localhost:50100/lightmin-server
      repository:
        remote:
          server-url: http://localhost:50000
      batch:
        #default jdbc
        repository-type: jdbc
        #default dataSource
        data-source-name: dataSource
        #default BATCH_
        table-prefix: BATCH_