server:
  port: 51500
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-batch-lightmin-server
  batch:
    job:
      enabled: false
    lightmin:
      server:
        discovery-enabled: true