server:
  port: 51500
spring:
  application:
    name: spring-batch-lightmin-server
  batch:
    job:
      enabled: false
    lightmin:
      lightmin-repository-type: map
      batch-repository-type: map
      server:
        heartbeat-period: 1000
        discovery-enabled: true