server:
  port: 9080
spring:
  application:
    name: address-migrator
  batch:
    lightmin:
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
        discovery-enabled: true
        discover-server: true
        server-discovery-name: spring-batch-lightmin-server
      #default jdbc
      batch-repository-type: jdbc
      #default jdbc
      lightmin-repository-type: remote
      #default dataSource
      batch-data-source-name: dataSource
      #default BATCH_
      repository-table-prefix: BATCH_
      #remote repository
      remote-repository-server-discovery-name: spring-batch-lightmin-server
      discover-remote-repository: true
logging:
  level:
    org.tuxdevelop: debug
